name: todak_commerce
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  intl: ^0.20.2
  floating_snackbar: ^1.0.5
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true


  assets:
    - assets/images/
    - assets/loftie/ 
    - assets/fonts/ 
 


  # Add this section for fonts
  fonts:
    - family: CircularStd 
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 800
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Regular.ttf
          weight: 400

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
